CREATE TABLE "Users" (
	"ID"	INTEGER NOT NULL,
	"User"	TEXT NOT NULL UNIQUE,
	"Pass"	TEXT NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE "AccessTokens" (
	"ID"	INTEGER NOT NULL ,
	"UserID"	INTEGER NOT NULL,
	"AccessToken"	INTEGER NOT NULL UNIQUE,
	"Device"	TEXT,
	"ExpireDate"	DATETIME DEFAULT '2000/01/01',
	FOREIGN KEY("UserID") REFERENCES "Users"("ID"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE "ExSets" (
	"ID"	INTEGER NOT NULL,
	"Title"	TEXT NOT NULL,
	"Description"	TEXT NOT NULL,
	"Enabled"	BOOLEAN NOT NULL DEFAULT 1,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE "Exercises" (
	"ID"	INTEGER NOT NULL,
	"ExSetID"	INTEGER NOT NULL,
	"Difficulty"	INTEGER NOT NULL DEFAULT 1,
	"Title"	TEXT NOT NULL,
	"Description"	TEXT NOT NULL,
	"Enabled"	BOOLEAN NOT NULL DEFAULT 1,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("ExSetID") REFERENCES "ExSets"("ID")
);
CREATE TABLE "Tests" (
	"ID"	INTEGER NOT NULL,
	"ExID"	INTEGER NOT NULL,
	"Test"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("ExID") REFERENCES "Exercises"("ID")
);
CREATE TABLE "Answers" (
	"ID"	INTEGER NOT NULL,
	"ExID"	INTEGER NOT NULL,
	"UID"	INTEGER NOT NULL,
	"Answer"	TEXT NOT NULL,
	"Response"	TEXT,
	"Approved"	BOOLEAN NOT NULL,
	"InitTime"	DATETIME NOT NULL DEFAULT 'now',
	"FinishTime"	DATETIME,
	FOREIGN KEY("UID") REFERENCES "Users"("ID"),
	FOREIGN KEY("ExID") REFERENCES "Exercises"("ID"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);